version: "3.8"

services:
  lms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-co-linh
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
